Repository bcgov/bcparis-service, pull requests merged in 2020-09, with the labels that each got.

#150 add issue template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/onboarding-request.md
Labels: documentation, enhancement

#149 Update pull_request_template.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: documentation, enhancement

#152 Increment Version
  pom.xml
Labels: good first issue

#161 Dependabot updates
  pom.xml
Labels: dependencies

#162 Remove exception details from warn error message
  src/main/java/ca/bc/gov/iamp/bcparis/Keys.java
  src/main/java/ca/bc/gov/iamp/bcparis/filter/LoggingFilter.java
  src/test/java/ca/bc/gov/iamp/bcparis/filter/LoggingFilterTest.java
Labels: bug
